### ISSUE TITLE
`Internal Server Error` with next.js@13.5.4

### ISSUE THREAD

**Issue by peakercope** [i18next/next-i18next#2214]
## 🐛 Bug Report

500 Internal Server Error with next.js version 13.5.4 in standalone build.

## To Reproduce

1.  clone repo https://github.com/peakercope/material-ui-nextjs-pages-router-ts-example
2. run `pnpm i`
3. run `pnpm build`
4. run `node .next/standalone/server.js`
5. open in browser `http://localhost:3000/`

## Actual behavior
Error page opened
<img width="530" alt="image" src="https://github.com/i18next/next-i18next/assets/10975462/52eaf1b9-bced-483c-8dc9-e642301791bc">

Terminal error:
```
Error: Cannot find module 'core-js/modules/es.array.map.js'
Require stack:
- /material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next-i18next@14.0.3_cziuidd23tbj2wqeyxn2xirvka/node_modules/next-i18next/dist/commonjs/config/createConfig.js
- /material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next-i18next@14.0.3_cziuidd23tbj2wqeyxn2xirvka/node_modules/next-i18next/dist/commonjs/appWithTranslation.js
- /material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next-i18next@14.0.3_cziuidd23tbj2wqeyxn2xirvka/node_modules/next-i18next/dist/commonjs/index.js
- /material-ui-nextjs-pages-router-ts-example/.next/standalone/.next/server/pages/_app.js
- /material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next@13.5.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/require.js
- /material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next@13.5.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js
- /material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next@13.5.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next.js
- /material-ui-nextjs-pages-router-ts-example/.next/standalone/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next@13.5.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next@13.5.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next-i18next@14.0.3_cziuidd23tbj2wqeyxn2xirvka/node_modules/next-i18next/dist/commonjs/config/createConfig.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next-i18next@14.0.3_cziuidd23tbj2wqeyxn2xirvka/node_modules/next-i18next/dist/commonjs/config/createConfig.js',
    '/material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next-i18next@14.0.3_cziuidd23tbj2wqeyxn2xirvka/node_modules/next-i18next/dist/commonjs/appWithTranslation.js',
    '/material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next-i18next@14.0.3_cziuidd23tbj2wqeyxn2xirvka/node_modules/next-i18next/dist/commonjs/index.js',
    '/material-ui-nextjs-pages-router-ts-example/.next/standalone/.next/server/pages/_app.js',
    '/material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next@13.5.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/require.js',
    '/material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next@13.5.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js',
    '/material-ui-nextjs-pages-router-ts-example/.next/standalone/node_modules/.pnpm/next@13.5.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next.js',
    '/material-ui-nextjs-pages-router-ts-example/.next/standalone/server.js'
  ]
}

```

## Expected behavior

Home page without an error should be opened

## Your Environment

- *runtime version*: node v18.18.0, pnpm v7.25.0 browser Google Chrome Version 117.0.5938.92
- *i18next version*: 
```json
    "i18next": "23.5.1",
    "next": "13.5.4",
    "next-i18next": "14.0.3",
    "react-i18next": "13.2.2"
```
- *os*: Mac

**Comment by adrai** [comment]
I'm not able to reproduce it:
<img width="1269" alt="image" src="https://github.com/i18next/next-i18next/assets/1086194/257cca5c-1429-46f4-bc1a-9f261282caf5">

**Comment by adrai** [comment]
And based on your error stacktrace, it's not related to next-i18next

**Comment by peakercope** [comment]
> And based on your error stacktrace, it's not related to next-i18next

Hello and thanks for the quick answer!
Do you think this issue should be opened in https://github.com/vercel/next.js repository?
Because without next-i18next everything works.

**Comment by adrai** [comment]
Like said, I'm not able to reproduce it, so it might be something in your local setup is wrong. Did you try to clone the repo in a fresh directory and try again? or on a different machine?

**Comment by peakercope** [comment]
yes sure, I made a clean installation several times with pruned pnpm store.
The issue is reproduced every time for production run ("node .next/standalone/server.js") on both my local machine  (AppleM1 / macos 13.6) and in docker container (node:18.17-alpine3.18).
`pnpm dev` works well

**Comment by adrai** [comment]
did you also try without pnpm, but with npm ?

**Comment by peakercope** [comment]
tried it now
it works with npm

**Comment by adrai** [comment]
might be a pnpm issue?

**Comment by natterstefan** [comment]
+1, I have the same issue as soon as I upgraded Next to 13.5.4.

```bash
Error: Cannot find module 'core-js/modules/es.array.map.js'
Require stack:
- /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js
- /var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js
- /var/task/node_modules/next-i18next/dist/commonjs/index.js
- /var/task/packages/web/.next/server/pages/_app.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/packages/web/___next_launcher.cjs
# ...
```

**Comment by octavioamu** [comment]
same here I had to rollback to [13.5.3](https://www.npmjs.com/package/next/v/13.5.3) seems a problem on next side but good to report here as took me a good day of work trying to figure out which package was failing. 
The problem happens when using getServerSideProps and serverSideTranslations the pages with getStaticProps and  serverSideTranslations works fine.

**Comment by meness** [comment]
Downgrading to next@13.5.3 didn't work. Here is the log:

```
-server.js',
    '/var/task/___next_launcher.cjs'
  ],
  page: '/collection/0x5a80497c8aba770421a8f6674c87182272e67e35'
}
Error: Cannot find module 'core-js/modules/es.array.map.js'
Require stack:
- /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js
- /var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js
- /var/task/node_modules/next-i18next/dist/commonjs/index.js
- /var/task/.next/server/pages/_app.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Ze.e.<computed>._module.Module._load (/var/task/___vc/__launcher/__launcher.js:14:1964)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js',
    '/var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js',
    '/var/task/node_modules/next-i18next/dist/commonjs/index.js',
    '/var/task/.next/server/pages/_app.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ],
  page: '/collection/0x5a80497c8aba770421a8f6674c87182272e67e35'
}
Error: Cannot find module 'core-js/modules/es.array.map.js'
Require stack:
- /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js
- /var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js
- /var/task/node_modules/next-i18next/dist/commonjs/index.js
- /var/task/.next/server/pages/_app.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Ze.e.<computed>._module.Module._load (/var/task/___vc/__launcher/__launcher.js:14:1964)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js',
    '/var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js',
    '/var/task/node_modules/next-i18next/dist/commonjs/index.js',
    '/var/task/.next/server/pages/_app.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ],
  page: '/collection/0x5a80497c8aba770421a8f6674c87182272e67e35'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by octavioamu** [comment]
> Downgrading to next@13.5.3 works. Here is the log:
> 
> ```
> -server.js',
>     '/var/task/___next_launcher.cjs'
>   ],
>   page: '/collection/0x5a80497c8aba770421a8f6674c87182272e67e35'
> }
> Error: Cannot find module 'core-js/modules/es.array.map.js'
> Require stack:
> - /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js
> - /var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js
> - /var/task/node_modules/next-i18next/dist/commonjs/index.js
> - /var/task/.next/server/pages/_app.js
> - /var/task/node_modules/next/dist/server/require.js
> - /var/task/node_modules/next/dist/server/next-server.js
> - /var/task/___next_launcher.cjs
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>     at /var/task/node_modules/next/dist/server/require-hook.js:54:36
>     at Module._load (node:internal/modules/cjs/loader:922:27)
>     at Ze.e.<computed>._module.Module._load (/var/task/___vc/__launcher/__launcher.js:14:1964)
>     at Module.require (node:internal/modules/cjs/loader:1143:19)
>     at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:64:28)
>     at require (node:internal/modules/cjs/helpers:121:18)
>     at Object.<anonymous> (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:35:1)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js',
>     '/var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js',
>     '/var/task/node_modules/next-i18next/dist/commonjs/index.js',
>     '/var/task/.next/server/pages/_app.js',
>     '/var/task/node_modules/next/dist/server/require.js',
>     '/var/task/node_modules/next/dist/server/next-server.js',
>     '/var/task/___next_launcher.cjs'
>   ],
>   page: '/collection/0x5a80497c8aba770421a8f6674c87182272e67e35'
> }
> Error: Cannot find module 'core-js/modules/es.array.map.js'
> Require stack:
> - /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js
> - /var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js
> - /var/task/node_modules/next-i18next/dist/commonjs/index.js
> - /var/task/.next/server/pages/_app.js
> - /var/task/node_modules/next/dist/server/require.js
> - /var/task/node_modules/next/dist/server/next-server.js
> - /var/task/___next_launcher.cjs
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
>     at /var/task/node_modules/next/dist/server/require-hook.js:54:36
>     at Module._load (node:internal/modules/cjs/loader:922:27)
>     at Ze.e.<computed>._module.Module._load (/var/task/___vc/__launcher/__launcher.js:14:1964)
>     at Module.require (node:internal/modules/cjs/loader:1143:19)
>     at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:64:28)
>     at require (node:internal/modules/cjs/helpers:121:18)
>     at Object.<anonymous> (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:35:1)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js',
>     '/var/task/node_modules/next-i18next/dist/commonjs/appWithTranslation.js',
>     '/var/task/node_modules/next-i18next/dist/commonjs/index.js',
>     '/var/task/.next/server/pages/_app.js',
>     '/var/task/node_modules/next/dist/server/require.js',
>     '/var/task/node_modules/next/dist/server/next-server.js',
>     '/var/task/___next_launcher.cjs'
>   ],
>   page: '/collection/0x5a80497c8aba770421a8f6674c87182272e67e35'
> }
> Error: Runtime exited with error: exit status 1
> Runtime.ExitError
> ```

Remove node_modules folder and install again

**Comment by octavioamu** [comment]
For changing versions you need to run the command npm pnpm or yarn remove and the add new one  and to be extra safe I prefer to delete node modules folder if I'm downgrading specially as many packages have dependencies also. Never edit the package.json versions  directly.

**Comment by samtgarson** [comment]
Seems to be an upstream issue https://github.com/vercel/next.js/issues/56357

**Comment by ajturpei** [comment]
Same issue when deployed to Vercel. Using v13.5.4, npm and next-i18next

**Comment by fabianuribe** [comment]
Same issue after upgrading Next to 13.5.4 and deploying to Vercel (issue is not present in local environment). Downgrading to 13.5.3 fixes the deployment.

```
…react@18.2.0/node_modules/next-i18next/dist/commonjs/config/createConfig.js',
    '/var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/appWithTranslation.js',
    '/var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/index.js',
    '/var/task/.next/server/pages/_app.js',
    '/var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ],
  page: '/'
}
Error: Cannot find module 'core-js/modules/es.array.map.js'
Require stack:
- /var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/config/createConfig.js
- /var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/appWithTranslation.js
- /var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/index.js
- /var/task/.next/server/pages/_app.js
- /var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js
- /var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at e.<computed>._module.Module._load (/var/task/___vc/__launcher/__launcher.js:14:2079)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/config/createConfig.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/config/createConfig.js',
    '/var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/appWithTranslation.js',
    '/var/task/node_modules/.pnpm/next-i18next@14.0.3_i18next@23.5.1_next@13.5.4_react-i18next@13.2.2_react@18.2.0/node_modules/next-i18next/dist/commonjs/index.js',
    '/var/task/.next/server/pages/_app.js',
    '/var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ],
  page: '/'
}
Error: Runtime exited without providing a reason
Runtime.ExitError
```

**Comment by samuelloranger** [comment]
Same issue deploying on Railway with next standalone.
Here is the stacktrace:
```shell
Error: Cannot find module 'core-js/modules/es.array.map.js'

Require stack:

- /app/node_modules/next-i18next/dist/commonjs/config/createConfig.js

- /app/node_modules/next-i18next/dist/commonjs/appWithTranslation.js

- /app/node_modules/next-i18next/dist/commonjs/index.js

- /app/.next/server/pages/_app.js

- /app/node_modules/next/dist/server/require.js

- /app/node_modules/next/dist/server/next-server.js

- /app/node_modules/next/dist/server/next.js

- /app/server.js

at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)

at /app/node_modules/next/dist/server/require-hook.js:54:36

at Function.Module._load (node:internal/modules/cjs/loader:873:27)

at Module.require (node:internal/modules/cjs/loader:1100:19)

at Module.mod.require (/app/node_modules/next/dist/server/require-hook.js:64:28)

at require (node:internal/modules/cjs/helpers:119:18)

at Object.<anonymous> (/app/node_modules/next-i18next/dist/commonjs/config/createConfig.js:35:1)

at Module._compile (node:internal/modules/cjs/loader:1198:14)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)

at Module.load (node:internal/modules/cjs/loader:1076:32) {

code: 'MODULE_NOT_FOUND',

requireStack: [

'/app/node_modules/next-i18next/dist/commonjs/config/createConfig.js',

'/app/node_modules/next-i18next/dist/commonjs/appWithTranslation.js',

'/app/node_modules/next-i18next/dist/commonjs/index.js',

'/app/.next/server/pages/_app.js',

'/app/node_modules/next/dist/server/require.js',

'/app/node_modules/next/dist/server/next-server.js',

'/app/node_modules/next/dist/server/next.js',

'/app/server.js'

]

}
```

**Comment by zewas-digital** [comment]
Removing the '^' of the next-version worked for me.
before:
`"next": "^13.5.3",
  "next-i18next": "^14.0.3",
  "i18next": "^23.5.1",
  "react-i18next": "^13.2.2"
`
after:
`"next": "13.5.3",
  "next-i18next": "^14.0.3",
  "i18next": "^23.5.1",
  "react-i18next": "^13.2.2"
`

**Comment by denizgokce-facturee** [comment]
> Removing the '^' of the next-version worked for me. before: `"next": "^13.5.3", "next-i18next": "^14.0.3", "i18next": "^23.5.1", "react-i18next": "^13.2.2" ` after: `"next": "13.5.3", "next-i18next": "^14.0.3", "i18next": "^23.5.1", "react-i18next": "^13.2.2" `

This worked for me as well

**Comment by samtgarson** [comment]
It looks like this might have been fixed in the [this PR](https://github.com/vercel/next.js/pull/56674) which is available in `13.5.5-canary.8`. 

(For those “removing the ^”, know that you’re simply pinning next to 13.5.3—downgrading from 13.5.4 has already been highlighted as a workaround for this issue.)

**Comment by CopyJosh** [comment]
Though the Internal Server Error is resolved, some pages stop hydrating translations. Only happens sometimes, and not on dev. Context looks like it still has all the data, but useTranslation hook doesn't have any langs. Trying to debug further but just mentioning if anyone else hits a similar experience.

**Comment by BaraaMohamed13** [comment]
@CopyJosh i have the exact problem ,  downgrading the next.js version to 15.5.3 indeed solved the server error but translations is not getting hydrated anymore on the hosted site , even though it works perfectly on local environment , will try to investigate further about this

**Comment by meness** [comment]
> Though the Internal Server Error is resolved, some pages stop hydrating translations. Only happens sometimes, and not on dev. Context looks like it still has all the data, but useTranslation hook doesn't have any langs. Trying to debug further but just mentioning if anyone else hits a similar experience.

Remove `ns` from `next-i18next.config.js` if it's defined.

**Comment by jbergstroem** [comment]
FWIW: Errors went away for me after updating to 13.5.5.
